### ISSUE TITLE
create an initial benchmark of 10 WASM programs

### ISSUE THREAD

**Issue by monperrus** [KTH/slumps#1]
incl. some inputs for each of them

**Comment by monperrus** [comment]
The test programs of wasmer could be a foundation: https://github.com/wasmerio/wasmer/tree/master/examples

**Comment by monperrus** [comment]
Other candidates: https://github.com/phayes/sidefuzz-targets

**Comment by shrin18** [comment]
https://github.com/WebAssembly/binaryen/tree/master/test/passes

I am not sure whether this will be helpful but I suppose we can experiment with the pre-compiled WASM programs here from binaryen, with several different ways and techniques of optimisations.

**Comment by shrin18** [comment]
Compiling from Rust to wasm: https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

**Comment by Jacarte** [comment]
We also can use SWAM [test cases](https://github.com/satabin/swam/tree/master/runtime/test/resources/spec-test)

**Comment by satabin** [comment]
I am currently working on writing the interpreter in a different way, which I hope will increase performances non-negligibly and make it easier to then port to GraalVM without rewriting everything. I’ll keep you updated.

**Comment by Jacarte** [comment]
Added the "hybrid" output as test subjects

**Comment by monperrus** [comment]
What do you mean by "hybdrid"?

**Comment by Jacarte** [comment]
I meant our experimentation with JS and WASM hybridation, but it is not a ready project yet :(

**Comment by monperrus** [comment]
The rust programs of https://github.com/phayes/sidefuzz-targets can all be compiled to WASM.

**Comment by shrin18** [comment]
The benchmarks from the following github repo was used to experiment the wasm minifications and the option `BINARYEN_DEBUG_SOUPERIFY=1` before using `wasm-opt` options on any wasm file

https://github.com/kripken/embenchen

**Comment by monperrus** [comment]
Excellent, could we add it to our pipeline?

**Comment by monperrus** [comment]
We have 27, let's close this, thanks for the great job!
