### ISSUE TITLE
Implement full pipeline

### ISSUE THREAD

**Issue by Jacarte** [KTH/slumps#16]
Implement full pipeline tool

We have the inner pieces and the vulnerabilities to test it. We can start to create the full pipeline

```
wasm -> souper IR -> candidate 1 -> LLVM IR -> wasm -> run_test_suite(), validate(), ...
                  -> candidate 2   
                  -> ...
                  -> candidate n
```

**Comment by jianguda** [comment]
1. __`*.wat`__`(WASM text format)` →  __`*.o`__`(WASM binary file)`
2. __`*.o`__`(WASM binary file)` → __`*.bc`__`(LLVM bitcode file)`
3. __`*.bc`__`(LLVM bitcode file)` → __`*.opt`__`(souper candidates)`
4. __`*.opt`__`(souper candidates)` → __`*.ll`__`(LLVM IR)`
5. __`*.ll`__`(LLVM IR)` → __`*.o`__`(WASM binary file)`

**Comment by Jacarte** [comment]
Prefect !

**Comment by Jacarte** [comment]
Hi @shrin18, We have the point **2.** right?

**Comment by jianguda** [comment]
Hey @Jacarte 
Maybe we could replace the first two steps with following three steps:

1. use __`wabt`__ to support `.wat -> .wasm -> .c`, following [this tutorial](https://github.com/WebAssembly/wabt/blob/master/wasm2c/README.md#tutorial-wat---wasm---c)
2. use __`clang`__ to support `.c -> .ll`, following [this link](https://dassur.ma/things/c-to-webassembly/)
3. use __`llvm-as`__ to support `.ll -> .bc` following [this document](https://llvm.org/docs/CommandGuide/llvm-as.html)

It would be much better if there is one way to directly support `.wat/.wasm -> .ll/.bc`

**Comment by shrin18** [comment]
> Hi @shrin18, We have the point **2.** right?

Hi, @Jacarte As per my understanding, last week we did a jump from **1. to 3.** . Currently compilation from .wast programs in benchmark programs is directly possible so that we can eliminate the llvm part as discussed. Also, souper candidates have two formats, textual human readable format in S-language of WASM and pure binary format. 

`wasm-opt --flatten --simplify-locals-nonesting --souperify input.wasm`

This code seems to accept a wasm file on input and so I used **wabt**  to convert wast to wasm. Does that seem logical ? @Jacarte @jianguda

**Comment by jianguda** [comment]
Hey @shrin18 Great!
Then our steps should be:
1. __`.wat`__ →  __`.wasm`__ (by `wat2wasm` from [`wabt`](https://github.com/WebAssembly/wabt))
`wat2wasm xxx.wat -o xxx.wasm`

2. __`.wasm`__ →  __`.opt`__ (by `wasm-opt` from [`binaryen`](https://github.com/WebAssembly/binaryen))
`wasm-opt --flatten --simplify-locals-nonesting --souperify xxx.wasm`

3. __`.opt`__ → __`.ll`__ (based on `utils/souper2llvm.in` from [`souper`](https://github.com/google/souper))
[scripts](https://github.com/KTH/slumps/tree/master/utils/souper2wasm)

4. __`.ll`__ → __`.bc`__ (by `llvm-as` from [`llvm`](https://llvm.org/docs/index.html))
`llvm-as xxx.ll`

5. __`.bc`__ → __`.opt`__ (based on `souper` from [`souper`](https://github.com/google/souper))
[scripts](https://github.com/KTH/slumps/tree/master/utils/souper_candidates)
6. __`.opt`__ → __`.ll`__ (same as step3)

----

if we need assembly filetype:
__`.ll`__ → __`.s`__ (by `llc` from [`llvm`](https://llvm.org/docs/index.html))
```
$ llc -march=wasm32 -filetype=asm xxx.ll
```
or we need binary filetype:
__`.ll`__ → __`.o`__ (by `llc` from [`llvm`](https://llvm.org/docs/index.html))
```
$ llc -march=wasm32 -filetype=obj xxx.ll
```

WDYT @Jacarte @shrin18

**Comment by jianguda** [comment]
#19

**Comment by jianguda** [comment]
Current solution for __`.opt`__ → __`.ll`__ is not so reliable, I feel it should be very ideal to improve its `souper2llvm.py` gradually based on our wast files.

This is [related discussion](https://github.com/google/souper/issues/334).

**Comment by jianguda** [comment]
Another feasible solution is to reuse some implementations inside wasmer, I made one [issue](https://github.com/wasmerio/wasmer/issues/871) there.

**Comment by jianguda** [comment]
Right now, step2 `.wasm → .opt` might have issues. Also, step3 `.opt → .ll` needs improvements.

My current plan is to study wasmer to directly support `.wasm → .ll`, then we only need to improve `souper2llvm.py` gradually.

**Comment by Jacarte** [comment]
> Right now, step2 `.wasm → .opt` might have issues. Also, step3 `.opt → .ll` needs improvements.
> 
> My current plan is to study wasmer to directly support `.wasm → .ll`, then we only need to improve `souper2llvm.py` gradually.

What about improvint wasm-opt in binaryen?

**Comment by jianguda** [comment]
> > Right now, step2 `.wasm → .opt` might have issues. Also, step3 `.opt → .ll` needs improvements.
> > My current plan is to study wasmer to directly support `.wasm → .ll`, then we only need to improve `souper2llvm.py` gradually.
> 
> What about improving wasm-opt in binaryen?

For wasm-opt, I am trying to locate `error: '%3' defined with type 'i1' but expected 'i32'`.

**Comment by shrin18** [comment]
We are trying to get valid candidates in souper in the .opt extension. On the input we are parsing .wasm or .wat files and as per the pipeline we should get required valid candidates for each of the .wasm or .wat program files. However the program throws some unexpected error regarding the syntax of the .wasm programs and it is different for each of the program per se. Further, it is good that the program succeeds in getting binary output from the llvm extensions and so we can narrow down the problem on the working of wasm-opt function.

**Comment by jianguda** [comment]
WAST -> WASM -> Souper -> LLVM -> WASM

**Comment by jianguda** [comment]
As discussed with @shrin18, for the __souper2llvm__ step, we have to improve existing solutions (Python or C++) in souper by ourselves.

I am doing the C++ plan at [`KTH fork`](https://github.com/KTH/souper), based on [`the "Souper codegen to LLVM IR" PR`](https://github.com/google/souper/pull/504).

**Comment by monperrus** [comment]
excellent. hopefully, we can contribute back upstream with a PR.

**Comment by jianguda** [comment]
Progress Note: We have tried the C++ plan and found currently it seems only support RHS, which is consistent with [this statement](https://github.com/google/souper/pull/504#issue-258080525). @shrin18 and I will discuss and decide our next step.

**Comment by monperrus** [comment]
OK, good progress!

**Comment by Jacarte** [comment]
@shrin18 and @jianguda...[this](https://github.com/KTH/souper/blob/35ef5225ff15f708da4388c0c1967bdfd62748f7/build_deps.sh#L24) is probably why we cannot reproduce the paper snippets. For some reason, the version here is 8.00 and not the 3.9 mentioned in the paper

**Comment by jianguda** [comment]
Hey @Jacarte 
This is one [sample](https://github.com/KTH/slumps/tree/master/utils/pipeline/_infer) which shows the correctness of most steps in our pipeline
(`.ll`->`.bc`->`.cand.opt`->`.lhs.opt`->`.rhs.opt`->`.new.ll`->`.new.bc`)

`infer.ll` was converted from [`infer.opt`](https://github.com/google/souper/blob/master/test/Tool/infer.opt) by using the [`souper2llvm.py`](https://github.com/google/souper/blob/master/utils/souper2llvm.in) script

**Comment by Jacarte** [comment]
The problem is when you try to generate the ll representation from C or another high-level :(

**Comment by Jacarte** [comment]
@shrin18, @jianguda the phi nodes from LLVM are an important part of souper. We should optimize IR with the -mem2reg option code before building the bc. 

```bash
opt -mem2reg -S ${name}.ll -o ${name}-mem2reg.ll 

llvm-as ${name}.ll -f
```

**Comment by Jacarte** [comment]
We patch the issue where the souperify pass was broken ([here](https://github.com/WebAssembly/binaryen/pull/2439) the PR) in binaryen. Now we can go directly from WASM to souper without the use of LLVM. This is better for our purposes because we can avoid initial optimization from LLVM. Preliminary results show even more candidates going directly from WASM, which means more variations for our final goal.

**Comment by jianguda** [comment]
We are able to reproduce experiments shown in the Souper paper, once we sync latest commits from the upstream repo to KTH/souper. Check [this issue](https://github.com/google/souper/issues/638) for more info.

**Comment by bbaudry** [comment]
that's a major milestone. well done!

**Comment by Jacarte** [comment]
We are closing it because we have the first implementation of this pipeline. We decided to improve the feed of souper going directly from WASM to Souper IR. The main idea is to [extend swam](https://github.com/KTH/slumps/issues/30) due to, first, it's a well-tested parser, second, we have no feedback from the binaryen PR with the Souper integration fix.
