### ISSUE TITLE
initial support for traces in Swam

### ISSUE THREAD

**Issue by monperrus** [KTH/slumps#2]
later, we'll support those traces in Javier trace comparison tool https://github.com/Jacarte/STRAC/

**Comment by Jacarte** [comment]
We will start wrapping memory access methods. Frame class in high-level interpreter of SWAM, here are the push/pop methods access the stack, the read methods, access the memory.

**Comment by Jacarte** [comment]
[Tracing advances](https://github.com/satabin/swam/pull/48)

**Comment by Jacarte** [comment]
Lets use [Common Trace Format](https://diamon.org/ctf/)

**Comment by Jacarte** [comment]
Merged in the master branch of the SWAM project

**Comment by monperrus** [comment]
cool!
