### ISSUE TITLE
Sync souper2llvm from latest souper

### ISSUE THREAD

**Issue by jianguda** [KTH/slumps#36]
from @shrin18 
_"We might want to have a look at [the latest PR](https://github.com/google/souper/pull/676) merged in the Souper Repo. I think [the brokenPR](https://github.com/google/souper/pull/504) as mentioned some time back by us in one of our issues to fix the souper2llvm script was finally merged. I think it is supposed to handle every souper instruction except phi and is a drastic improvement over [the Pass code](https://github.com/google/souper/blob/master/lib/Pass/Pass.cpp) since it parses only the RHS candidates generated. I think Jian and I worked on integrating some of the lines of the code previously in our bash pipeline for generating the RHS but now since its merged we only need to use the souper2llvm script. Maybe an option to consider alongside SWAM."_

Maybe we shall sync KTH/souper with the latest google/souper and make some changes to our bash pipeline in the near future? @Jacarte

**Comment by shrin18** [comment]
Yes I think that will make the work easier for us I think.

**Comment by Jacarte** [comment]
Hmm

Remember that the souper2llvm transform the SouperIR to a [selfcontained](https://github.com/google/souper/blob/master/tools/souper2llvm.cpp) function without the global information of the original module. I think this script is only a demo tool. The full integration is in the opt pass compiled with souper.

**Comment by jianguda** [comment]
I have rebased and there are not many differences.
