### ISSUE TITLE
identify in Souper how to keep intermediate non-optimal versions

### ISSUE THREAD

**Issue by monperrus** [KTH/slumps#4]

**Comment by jianguda** [comment]
Hey @Jacarte 
Theoretically all optimization candidates are valid. Have you found some abnormal cases?

Souper relies on [`void ExtractExprCandidates(...)`](https://github.com/google/souper/blob/master/lib/Extractor/Candidates.cpp#L925) to generate optimization candidates.

**Comment by jianguda** [comment]
Hey @Jacarte 
Before applying solver, optimization candidates are not necessarily all valid. I will fix this soon.

**Comment by monperrus** [comment]
in which document is that explained?

**Comment by jianguda** [comment]
Hey I read [<Future Directions for Optimizing Compilers>](https://arxiv.org/abs/1809.02161) and at page5 it says __"Implement solver-based tools for finding incorrect optimizations, not-weakest preconditions, groups of optimizations that either subsume each other or
undo each other, etc."__, then I learnt that it is not necessarily to generate valid candidates before solvers. I did not find something in Souper's documents or its paper.

**Comment by jianguda** [comment]
Hey I read [<Future Directions for Optimizing Compilers>](https://arxiv.org/abs/1809.02161) and at page5 it says _"Implement solver-based tools for finding incorrect optimizations, not-weakest preconditions, groups of optimizations that either subsume each other or
undo each other, etc."_, then I learnt that it is not necessarily to generate valid candidates before solvers. I did not find something in Souper's documents or its paper.

**Comment by jianguda** [comment]
Hey I read [Future Directions for Optimizing Compilers](https://arxiv.org/abs/1809.02161) and at page5 it says _"Implement solver-based tools for finding incorrect optimizations, not-weakest preconditions, groups of optimizations that either subsume each other or
undo each other, etc."_ so it is not necessarily to make sure generated candidates are valid before any solvers. I did not find related content at souper's document or its paper.
