### ISSUE TITLE
SLUMPs superoptimization & randomization on muladd

### ISSUE THREAD

**Issue by orestisfl** [KTH/slumps#46]
We should execute and upload the results of the superoptimization & randomization  pipeline with https://raw.githubusercontent.com/kth-tcs/verificatum-vjsc/master/src/wasm/muladd.c

**Comment by Jacarte** [comment]
On it

**Comment by monperrus** [comment]
@Jacarte any news on this? Thanks!

**Comment by monperrus** [comment]
that's done
