### ISSUE TITLE
implement the way back from Souper IR to WASM

### ISSUE THREAD

**Issue by monperrus** [KTH/slumps#5]

**Comment by jianguda** [comment]
__Souper IR → LLVM IR__
I will start from Souper's [souper-check.cpp](https://github.com/google/souper/blob/master/tools/souper-check.cpp)

__LLVM IR → WASM__
`llc-7 -mtriple=wasm32-unknown-unknown` ([blog](https://medium.com/@richardanaya/write-web-assembly-with-llvm-fbee788b2817))

**Comment by monperrus** [comment]
per which PR?

**Comment by jianguda** [comment]
[#13](https://github.com/KTH/slumps/pull/13)

**Comment by Jacarte** [comment]
Reformulated in #42
